### ISSUE TITLE
Извлечение ключевой информации из распарсенных данных

### ISSUE THREAD

**Issue by PtichkinSergey** [moevm/mse1h2024-assistant#20]
Необходимо избавиться от мусора в считываемом json с данными из moevm.
Можно использовать что то на подобии библиотеки NLTK.

**Comment by Andrexus23** [comment]
нужно попробовать изменить scrape_page и recursive_scrape в парсере так, чтобы прямо в процессе рекурсивного обхода выкидывался мусор из данных, например, последовательности байт.
![image](https://github.com/moevm/mse1h2024-assistant/assets/52220237/a95cdb13-632e-4e99-9b4f-688a8155c456)

 с целью немного ускорить парсер и упростить задачу выделения ключевых слов
