### ISSUE TITLE
Настройка ответа модели по вопросу из выбранного контекста

### ISSUE THREAD

**Issue by Andrexus23** [moevm/mse1h2024-assistant#54]

**Comment by PtichkinSergey** [comment]
Определить возможную проблему, почему модель не отвечает на вопрос по выбранному контексту, при правильном запросе.

**Comment by PtichkinSergey** [comment]
Задача всё ещё актуальна, поскольку модель перестала отвечать не только на некорректные вопросы, но и на часть корректных
